version: "3.7"
services:
  db:  
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=easy
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data 
  sansaar:
    build:
      context: .
      dockerfile: Dockerfile
    image : sansaar
    container_name: nodejs
    depends_on:
    - db
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: easy
      DB_NAME: ndb
volumes:
  db:
    driver: local
